runtime: python313
entrypoint: streamlit run app.py --server.port=$PORT --server.address=0.0.0.0 #gunicorn -w 1 -k uvicorn.workers.UvicornWorker main:app
env_variables:
  ENVIRONMENT: "PRODUCTION"

handlers:
- url: /.*
  script: auto